### ISSUE TITLE
Statistics page gives 500 error after event ends

### ISSUE THREAD

**Issue by CorpulentBrony** [snowpity/concrescent#1]
The convention page (/admin/statistics.php) gives a 500 error after the day of the con has passed.

**Comment by Wolvan** [comment]
Seems to happen once the date/time in set in the config file passes.
Potentially also related to a big dataset in the database, although that seems unlikely.

**Comment by KahasKahas** [comment]
I tested with past dates to no avail.
The page is quite complex and it may be related to a very specific set of broken data.
