### ISSUE TITLE
Emoji in long text entry fields cause 500 HTTP errors

### ISSUE THREAD

**Issue by CorpulentBrony** [snowpity/concrescent#14]
Steps to reproduce:

1. Begin staff application
2. Put emotes in the more information/freeform posting field at the end of the application (specifically 🗿 and 🖕)
3. Attempt to submit the form

What happens:

![image](https://github.com/snowpity/concrescent/assets/12999979/04985377-924a-4f9f-80d0-dc167b0854ec)

What should happen:

Application should be successfully submitted

**Comment by KahasKahas** [comment]
Seems like the database connection is initialized with the wrong charset.

**Comment by KahasKahas** [comment]
Fixed 

![image](https://github.com/snowpity/concrescent/assets/149937112/352f8099-c41a-42bf-bfb1-c9f86d333f19)
![image](https://github.com/snowpity/concrescent/assets/149937112/f03b611f-ffe9-4e2a-8bdb-3fc272cf2c52)

**Comment by KahasKahas** [comment]
@CorpulentBrony The fix is live on production.

Please get back to me if it still doesn't work.
