### ISSUE TITLE
Magic link doesn't always work

### ISSUE THREAD

**Issue by CorpulentBrony** [snowpity/concrescent#4]
There are many reports of attendees trying to use the "magic links" to login and not being able to access their information.

**Comment by Wolvan** [comment]
I believe this is related to #2 and the cookie issue. Once again, no confirmation here.

**Comment by KahasKahas** [comment]
> I believe this is related to #2 and the cookie issue. Once again, no confirmation here.

It seems to happen specifically when there is no legacy mode `L` cookie. 👍

**Comment by KahasKahas** [comment]
The cookie lived for 2 hours, hence the apparently "random" behaviour.

The legacy detection and switch to CM3 webapp has been removed and the bug, if this is the correct reproducer is resolved

Also resolves #2.
